name: build-and-test

on:
   push:
    paths:
     - '**/*.kt'

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Run tests
        working-directory: claqueta_tfg/  # Establece la ruta correcta al directorio con el archivo gradlew
        run: |
          chmod +x gradlew  # Asegúrate de que el archivo gradlew sea ejecutable
          ./gradlew test